### ISSUE TITLE
python and java basic programs

### ISSUE THREAD

**Issue by Ishnoor-kaur** [AdarshAddee/Hacktoberfest-2022#1]
hey, i have some programs on array and string manipulation in java and some others in python. i would be happy to contribute those to your repo. please assign me this :)

**Comment by jawadkhanpk** [comment]
Hi, I would like to contribute to this issue. Please assign me this issue

**Comment by jawadkhanpk** [comment]
@AdarshAddee I have some basic and advance programs which I would like to contribute

**Comment by AdarshAddee** [comment]
@Ishnoor-kaur @jawadkhanpk   Kindly add only intermediate & advance programs.
